### ISSUE TITLE
Create controller class to handle intro and outro sequences

### ISSUE THREAD

**Issue by justKD** [systers/powerup-iOS#255]
## Description
As a developer,
I need to create a class to handle presentation and interaction for intro and outro sequences,
so that I can ensure the new functionality conforms to efficient model-controller principles and is sufficiently sandboxed from existing code.

## Mocks
n/a

### Update [Required]
- [ ] handles presenting parent view container
- [ ] references a separate class as its datasource
- [ ] handles animations and interactions
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.
