### ISSUE TITLE
Create class to handle popovers during a scenario

### ISSUE THREAD

**Issue by justKD** [systers/powerup-iOS#257]
## Description
As a developer,
I need create a controller class to handle presenting and interactions for in-sequence popovers,
so that I can ensure the new content follows efficient model-controller principles, and is sufficiently sandboxed from existing code.

## Mocks
n/a

### Update [Required]
- [x] handles presenting parent view
- [x] handles presenting media from the model class
- [x] handles interactions
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.
